### ISSUE TITLE
Jobs stuck in inactive state

### ISSUE THREAD

**Issue by mikemoser** [Automattic/kue#130]
Jobs get stuck in the inactive state fairly often for us.  We noticed that the length of `q:[type]:jobs` is zero, even when there are inactive jobs of that type, so when getJob calls `blpop`, there is nothing to process. 

It looks like this gets set when a job is saved and the state is set to inactive using `lpush q:[type]:jobs 1`.  We're wondering if this is failing in some cases and once the count is off, jobs remain unprocessed.

Has anyone else seen this issue?

**Comment by cburatto** [comment]
I am having this issue and it behaves as describer by @knation -- when the queue is inactive for too long (ex.: test environment is up over the weekend) -- any new jobs to that worker will get stuck. When I restart the worker, it processes the job. Is there any more information about this? I'll try @knation solution, but maybe a keep alive should standard.

**Comment by behrad** [comment]
> when the queue is inactive for too long

if your case is when Kue workers are idle for a long time, that is a different issue, and could be related to node_redis and it's connection properties. It may be the connection which is dropped for inactivity.
Can you investigate more and open another issue if so !?

**Comment by cburatto** [comment]
Thanks for pointing to a direction. I suspect using a `keep_alive : true` option when creating the queue might help. I'll test asap, but if you have any information or know of any drawbacks, that would help.

     var queue = kue.createQueue({
				  prefix: 'q',
				  redis: {
					"host" : REDIS_KUE_HOST,
					"port" : REDIS_KUE_PORT,
                    "socket_keepalive" : true
				  }
				});

**Comment by mathieugerard** [comment]
I recently moved my Kue workers from Heroku to a Ubuntu machine on Azure. On heroku everything works fine but on Azure I have the same issue of workers stopping taking jobs as described above.

As soon as the Azure workers get idle for about 5 minutes, they stop taking jobs forever. If I restart them, they start processing jobs again.
In the meanwhile, the workers on Heroku running exactly the same code keep taking jobs anytime, even after days being idle.

I do not see anything on the Azure or the Redis log saying anything is wrong, but i suspect it is indeed the BLPOP which is never responding.

Since both workers are running the exact same code, I would believe this could be linked to a configuration on the Ubuntu Server 14.04.4 machine or the environment. Any idea where to search?

**Comment by behrad** [comment]
> As soon as the Azure workers get idle for about 5 minutes

This may mean that your redis client connections are being closed or dropped after some idle time, Some saw this on cloud deployments. You can monitor your redis instace connections, or increase idle connection timeout, I don't remember the option name in node_redis, you can search Kue issues for that.

**Comment by victusfate** [comment]
Ok so I ran into something with gearman workers/jobs a few years back. I believe it could be related as I can consistently recreate stuck jobs by queueing them up and killing the worker.

Whenever our workers (which aren't running in the same process space as the queue) restart or are killed (any deployment), they are not cleanly deregistering:

- deleting worker
- resetting all active jobs to inactive
- calling done w/ error

This happens on every code push when I'm deploying (to heroku, locally, ec2, etc) and this is highly correlated with where I run into the stuck jobs/queue. I noticed the reference to [gracefully shutting down](https://github.com/Automattic/kue#graceful-shutdown) the queue or restarting, but nothing about the workers that exec the jobs themselves.

What I believe is needed is something like the below code (I'm testing today locally since I recreate the stuck queue - version -> master git+https://git@github.com/Automattic/kue.git )

```
process.on( 'SIGINT', function() {
  // delete any active workers in this process
  // reset any active jobs in this process to inactive, and ensure their done w/ error is called
  process.exit( );
})

```

If memory serves, there may be other signals we'll need to listen to as well. Please let me know if there's a simple wrapper I can add somewhere, I'm hoping I can add it safely to my Job class.

**Comment by victusfate** [comment]
Ok put together a gist with graceful queue and worker shutdown. I'm still seeing a stock active job, so I think worker pause is not triggering active jobs into an inactive state.

Here's the gist:
https://gist.github.com/victusfate/1e2ce9eb73de32b78d2690d660f0f9c8

**Comment by victusfate** [comment]
Updated the gist above to check if a job is active, and set its state to inactive so other workers or this worker can pick it up when they resume.

**Comment by manast** [comment]
If you really care about this issue, latest bull is really at par feature wise with kue but with a non polling, and mostly atomic design, why wait to kue 1.0 when you can use bull? :) https://www.npmjs.com/package/bull

DISCLAIMER, I am the author of the package, I started it out of the frustration of some of the long standing issues with kue, which still today are not completely fixed, and can tell by experience that it is not completely trivial to rewrite everything using lua scripts and blocking redis calls...

**Comment by Caspain** [comment]
To remedy this issue, just create another job that periodically wakes the queue roughly every 1 minute then when complete , just remove. This way all jobs will get awoken and never get truly stuck.

**Comment by victusfate** [comment]
But who watches the Watchmen? @Caspain

**Comment by victusfate** [comment]
@knation do you have a complete snippet for the keep alive interval. We're still seeing stuck inactive jobs only in our dev environment likely related to long periods of inactivity.

Is this sufficient? I noticed your ... above

```javascript
queue.process('stuck_queue', 10, function(job, done) {
  if (job.data.keepAlive) return done();
});

setInterval(function() { queue.create('stuck_queue', { keepAlive: true }).save(); }, 300000);
```

**Comment by knation** [comment]
@victusfate Honestly, we abandoned this quite some time ago and migrated to a pubsub message system. That said, I believe it's close to what we had.

**Comment by victusfate** [comment]
Thanks @knation I ended up not needing it (just had a worker issue).

**Comment by christianguevara** [comment]
Hey @victusfate maybe can you comment what kind of issues ? i some times get stucked jobs could not find the reason yet.

**Comment by victusfate** [comment]
I do a graceful job to inactive shift on process kill or term and that normally handles any stuck jobs. My issue was just a faulty worker

**Comment by theoutlander** [comment]
Still facing this issue! I have all the error handlers, etc. as mentioned in the documentation. There was no failed job event raised either. I wasted the last three weeks implementing a solution with Kue/Redis that's completely unreliable! Going to switch to something else... will try Bull and if that doesn't work, I will move to RabbitMQ.

**Comment by theoutlander** [comment]
The number of jobs that are hung every time are equal to the number of parallel threads processing jobs.

**Comment by manast** [comment]
@theoutlander try bull which has a similar API to Kue, and if you need help ask in the gitter channel: https://gitter.im/OptimalBits/bull
The reason I wrote bull in the first place was due to the stuck jobs issue.

**Comment by theoutlander** [comment]
@manast Thanks for creating this. I'm loving it so far. Have ran into a weird issue today (https://github.com/OptimalBits/bull/issues/170)....not sure why. It went away after a while / restarting the IDE (Webstorm).

I haven't faced any issues with stuck jobs so far! Good work! And great job keeping a similar API...the transition was seamless!
