### ISSUE TITLE
function inside of process executed with previous data

### ISSUE THREAD

**Issue by HarryHong** [Automattic/kue#570]
Hi, 
I am trying to implement something like:
```javascript
var a_function = function (data_id) {
     kue = new require('kue').createQueue();    //create
     
     Clean_this_kue();                 //clean up kue first
     kue.create('Atype').save();   //initiate

     kue.process('Atype', function (jobs, done) {
    		logger.warn(jobs.id,data_id);                             // sample Issue:  jobs.id:  3194, data_id: 10
    		some_method(data_id, function (err, result) {
    	           logger.warn(jobs.id,data_id);                         // sample Issue:  jobs.id:  3194, data_id: 9
	            if (result === 'finished') {
	            	jobs.remove();
		    } else {
			 var delay = 500; // every half sec
			kue.create('Atype').delay(delay).save();
			jobs.remove();
		    }
	        });
	        done();
    });
```

I have this function called upon event, "data_id" is updated each main function call.

It works on first run
but "data_id" in "some_method(data_id)" does not get updated after, I observed it get called with data_id from last job.

Any idea on this?
some_method(data_id)" does not get updated after, I observed it get called with data_id from last job.

Any idea on this?

**Comment by behrad** [comment]
you are calling a `.process` per each `a_function` call, so creating many workers (job processors) and thus you won't be sure wich process function will handle the next created job :)
So the way you are thinking and arranging your code is semantically wrong, I don't see what you are exactly trying to achive, but you may want to call process once. 

Closing this since it is not related to Kue.

**Comment by behrad** [comment]
you can post here if you are still having problems in your code
