### ISSUE TITLE
Lock client prevents kue to exit the process after shutdown

### ISSUE THREAD

**Issue by jesucarr** [Automattic/kue#578]
See issue #574, and comment https://github.com/Automattic/kue/issues/574#issuecomment-93496632 for full explanation.

**Comment by behrad** [comment]
@jesucarr would you test if promotion timer issues fixed in latest commit?

**Comment by jesucarr** [comment]
No, the process is still stuck after "queue closed" is done

**Comment by behrad** [comment]
Would you please post the code snippet of your shutdown so that I can run & debug it.

**Comment by behrad** [comment]
you are using 0.9.0 (master) and search indexes are at their default (off), right?

**Comment by jesucarr** [comment]
kue = require('../lib/kue');

    queue = kue.createQueue({
      disableSearch: true
    });

    job = queue.create('test job', {
      num: 1
    }).attempts(2).delay(1000 * 10).backoff({
      type: 'exponential'
    }).save(function(err) {
      if (err) {
        return console.log(err);
      }
      console.log('job added', job.id);
      return queue.shutdown(function(err) {
        return console.log('queue closed');
      });
    });

**Comment by behrad** [comment]
this is because of the extra lock client which warlock uses, and kue cannot end it at shutdown, I saw a bug when you change warlock modules redis client object: https://github.com/TheDeveloper/warlock/issues/11
I should re-implement a distributed lock inspired by warlock, since no response to that issue is seen...

And some points about your code:
1) in kue 0.9.0 search is off by default, no need to set disableSearch any more
2) if you are not creating workers (calling `.process`) there's no need to call `shutdown`

**Comment by behrad** [comment]
So this is not related to promotion timer and will be renamed if you don't mind :)

**Comment by behrad** [comment]
fixed by forking warlock

**Comment by behrad** [comment]
https://github.com/Automattic/kue/commit/73a8bb7f06c8abb5cf75695c1f23f1676c833893
