### ISSUE TITLE
Call unlock after all jobs are processed by promotion/ttl timers

### ISSUE THREAD

**Issue by behrad** [Automattic/kue#601]
https://github.com/Automattic/kue/issues/590#issuecomment-99208300

**Comment by schnie** [comment]
I'm new to kue but I'd love to help out and possibly send a PR for this, but I'm not positive on what needs to happen.  In your comment on #590, you mentioned calling `unlock()` pessimistically after all jobs `inactive` are done.  I'm thinking this mean that since inactive is an async operation, that we need to wait until all of the asyc `inactive` calls have completed, before calling `unlock()`.  Seems like we could create an array of promises, then call `unlock()` after all are completed.  Does this sound ok?  Are there any objections on adding a promise lib as a dependency?

**Comment by schnie** [comment]
Went ahead and took a stab at a PR with #605.  Instead of using promises, I used loadsh's `after` to achieve the same result and reduce the need for a new dependency.  I've tested this on an application where I was seeing multiple processes promote the same job, resulting in multiple execution of the job.

**Comment by behrad** [comment]
thank you for the PR @schnie 
Are you telling me that this change didn't solve it?

**Comment by schnie** [comment]
Sorry, maybe I phrased that wrong.  I tested it on the application that was having this problem, and it definitely has fixed the issue for me.

**Comment by behrad** [comment]
are you still having a problem or shall I close this?

**Comment by behrad** [comment]
I mean after the merge... ;)

**Comment by schnie** [comment]
Yep, should be fixed after the merge.  Thanks!

**Comment by behrad** [comment]
great, thank you @schnie
