### ISSUE TITLE
Call done outside process callback

### ISSUE THREAD

**Issue by makkeu** [Automattic/kue#637]
Is this scenario possible? I haven't found a solution yet. I could keep inner state in a module, but that is not optimal, as I want to keep things stateless.

```
//this is simplified sample code, may contain typos etc
//I'd like to keep this module and JobHandler stateless.
//JobHandler just fires job processing and gets
//result events, but no necessary in same order than jobs are started. 

var handler = new JobHandler(); //custom job handler

handler.on('jobcomplete', function(results) {
  // results.kueId is reference to kue job id
  kue.Job.get(results.kueId, function(err, job){
    // complete job here and emit job's complete event
    // can I access job's done function here?
    // or manually emit job's complete event
    job.complete(); //this doesn't seem to fire event
  });
});

var job = queue.create(...)
.on('complete', function() { // need to get this event })
.save();

queue.process('type', function(job, done) {
  //done is not called here
  handler.startJob(job);
  // this will send events when jobs are completed, but not necessary in same order
  // so I can't do .on('jobcomplete', done);
});

```

I have tried to find correct worker by job's workerId and then call it's emitJobEvent('complete', job, results) . While it does fire the complete event correctly, it produces following error:
```
node_redis: no callback to send error: ERR wrong number of arguments for 'incrby' command

Error: ERR wrong number of arguments for 'incrby' command
    at ReplyParser.<anonymous> (/Users/markku/Projects/richiemaggio/server/node-job-server/node_modules/kue/node_modules/redis/index.js:317:31)
    at ReplyParser.emit (events.js:95:17)
    at ReplyParser.send_error (/Users/markku/Projects/richiemaggio/server/node-job-server/node_modules/kue/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/Users/markku/Projects/richiemaggio/server/node-job-server/node_modules/kue/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/Users/markku/Projects/richiemaggio/server/node-job-server/node_modules/kue/node_modules/redis/index.js:547:27)
    at Socket.<anonymous> (/Users/markku/Projects/richiemaggio/server/node-job-server/node_modules/kue/node_modules/redis/index.js:102:14)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:765:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
```

**Comment by behrad** [comment]
I don't see why you are complicating things when the only healthy way to complete a job is calling `done` handle when your `job finished logic` arrives. if you want it out of your `process` then you can easily do
```js
queue.process('type', function(job, done) {
  handler.startJob( job, done );
});
```
to pass the `done` handle to the handler object. 

I normally use `on('job complete'...)` to do extra logic/cross cutting concerns on finished jobs, since it is loosely called when `done` is called by a worker :)

**Comment by makkeu** [comment]
I know I can pass the done callback. The issue for me is that when I start the job, I'm required to fire a external process thru network, and fetching results from Amazon SQS queue. This is a thing that is out of my control. When I poll the results from the sqs, it is not guaranteed that the result I get is actually the result of that specific job. Process that gets the job's result might be a different to the one which initiated it, so it can't have access to the done callback. This felt like the easiest way to solve this particular case since I'm going to use kue anyway for other types of jobs.

Would there be problems, if the worker instance keeps reference to that done function for the current job, so it can be called by accessing worker instance of the job? I'm not that familiar with this module, so I might be totally wrong.

in worker.js
```
  var doneCallback = createDoneCallback( job.id );
  job.doneCallback  = doneCallback; // keep reference by adding this (probably needs to release it when job is processed?)
```

---
in kue application
```
handler.on('jobcomplete', function(data) {
  kue.Job.get(data.kueId, function(err, job){
    if (err) {
      console.error(err);
      return;
    }
    var worker = queue.workers.filter(function(w) {
      return w.id === job.workerId;
    });

    if (worker && worker[0]) {
      if (worker[0].job) {
        worker[0].job.doneCallback(null, data);
      }
    }
  });
});

queue.process('type', function(job, done) {
  handler.startJob( job );
});
```

But if this can't be done, I need to rethink my approach.
Anyway, thanks for your response.

**Comment by behrad** [comment]
1. the job instance you wanna call done upon is fetched by `kue.Job.get` and is not a local job object. Even  `job.doneCallback  = doneCallback;` won't help since functions are not serialized on redis in kue.

2. this is not a pretty solution,
```js
var worker = queue.workers.filter(function(w) {
  return w.id === job.workerId;
});
```
you won't know if you are in the correct process that has the original worker (if you are using node.js `cluster` or scaling out). You'd better not to rely on worker internals.

3. Kue is designed for local job processors, so the completion marker is also local. I hadn't seen a case where workers logic is actually a WebService or external service logic. For this you have two situations:
  3.1. orchestrate/mediate your external service req/resp with Kue jobs and use events to start/finish jobs if you can!
  
  3.2. patch kue to expose the job completion logic https://github.com/Automattic/kue/blob/master/lib/queue/worker.js#L159-L198 as an independent-to-worker-context function in `Job` class and call that!


I yet don't know your specific limits/requirements or I would suggest more concrete solution based on 3.1

**Comment by behrad** [comment]
And remember the original worker would be busy until `done` is called, if you take it out you should decide whether to call done soon (to free the worker for next job) or to reserve done in memory and use pub/sub to receive the jobcomplete by the original process. So this patching would ruin all Kue concept.

this much I know of your case, and If I was to go this way, I preferred to store done in memory and use redis pub/sub (you can also use another kue job in chain) to receive the external service event from outside.

**Comment by makkeu** [comment]
Thanks for the detailed explanation. I had similar concept in mind (3.1) and will probably try to solve the problem that way.
