### ISSUE TITLE
removeBadJob(id) does not removes id from q:jobs:TYPE:STATE

### ISSUE THREAD

**Issue by svbatalov** [Automattic/kue#661]
Hi.

Sometimes I see error messages like `[Error: job "11066" doesnt exist]` in my logs (can't make reproducible example yet; seem to happen after periods of heavy load). After some research I found that some obsolete ids remain in `q:jobs:TYPE:complete` etc, for instance:
```
127.0.0.1:6389> zcard q:jobs:complete
(integer) 14
127.0.0.1:6389> zcard q:jobs:play:complete
(integer) 24
```
So there are 10 extra ids in per-type zset. I dunno if it is related, but I noticed that `removeBadJob()` function does not removes anything from `q:jobs:TYPE:STATE`, only from `q:jobs:STATE` zsets. Is it an intended behaviour or a bug?

Kue version 0.9.3.

Thanks.

**Comment by behrad** [comment]
in some race cases there's no type information in job hash index (they are removed) but it still remains in type:state ZSET. in this situation `removeBadJob` would be unable to clean that id from ZSET. We may be able to work around this however when switching to server-side/atomic job management in later version, this will completely fade out.

**Comment by svbatalov** [comment]
OK, waiting for the next release. Closing for now.

Thanks for response!

**Comment by stouf** [comment]
Hi there!

Just a quick comment to know if this issue is still unresolved? I browsed the [release history](https://github.com/Automattic/kue/blob/master/History.md) from the version 0.9.3 to the latest and did not find any notes about it.

If this issue is still unresolved:

- do you have any idea when/if it will be addressed?
- do you have any advise as for how to handle it? Is ignoring those messages the only possibility at the moment?

Thanks in advance :)
