### ISSUE TITLE
DO NOT use this library if you need sequential order execution your jobs.

### ISSUE THREAD

**Issue by misterjt** [Automattic/kue#703]
I spent two week of development with kue, and just yesterday i noticed weird sorting.
Just think twice before using this library, if you need sequential order execution your jobs. 
Developers probably forgot about kue and will never fix it.
#691
#693

**Comment by danpantry** [comment]
> Developers probably forgot about kue and will never fix it.

I know certainly that TJ holoway (one of the lead devs) [stopped using node a while ago](https://medium.com/@tjholowaychuk/farewell-node-js-4ba9e7f3e52b) and only wants to continue to maintain `koa`

**Comment by pursual** [comment]
Any suggestions on a sequential task library?

**Comment by misterjt** [comment]
https://github.com/OptimalBits/bull

**Comment by hockeytim11** [comment]
#708 
Just wanted to reference a fix I worked on.

**Comment by behrad** [comment]
> I spent two week of development with kue, and just yesterday i noticed weird sorting.

If you've read the docs and searched issues carefully you would find out that Kue is a priority Queue not a sequential task library (however you can use it as a sequential task library) and that there exists an issue with specific task ids (10, 100, 1000, ...) in job orderings...
That means you are infected if you are creating many jobs concurrently or your queue contains many jobs. e.g. you will be hit by job id 10 for the first time, (if 9 and 10 are queued up, 10 will be run sooner)



> Developers probably forgot about kue and will never fix it

I'm trying to improve Kue for about 2 years now. Since this is a one-man work for now, my busy hours delays kue 1.0 release, however any members, helpers, ... are welcome.


> DO NOT use this library if you need sequential order execution your jobs

I can't figure out why are you trying to achieve with this kind of statement. You are free to use everything you want/need/prefer. However this is not normal to open up an issue with such a title.

**Comment by behrad** [comment]
> Just wanted to reference a fix I worked on.

I'll try to check you PR thank you @hockeytim11

**Comment by desaurabh** [comment]
### Please add a disclaimer/note

> This library is not ideal solution for sequential jobs neither. works well with multiple jobs inside a parent job.


**Oberserved problem** - Variables are not changing for the consecutive jobs.

### Pic 1 

Passed, shows the 2 consecutive passed jobs without any errors. 
![passed](https://user-images.githubusercontent.com/7892696/55639476-1f8e6b80-57e7-11e9-8329-25f7ca97b92c.png)

### Pic 2 

Failed, shows 2 following jobs, they failed due to file library was searching for the previously moved file 
![failed](https://user-images.githubusercontent.com/7892696/55639655-87dd4d00-57e7-11e9-86dc-65aa92887059.png)

I have tried refractoring my code twice even tried different approach with a workaround and that took me around 10-12 days but unfortunately this problem still persists.
