### ISSUE TITLE
0.10.x should be a major version increment

### ISSUE THREAD

**Issue by jeremiahlee** [Automattic/kue#758]
The [Upgrade Checklist](https://github.com/Automattic/kue/wiki/Upgrading-to-0.10.x) states upgrading the library may break existing jobs. There isn't much information on the risk of this or what can be done to assess risk. The only way to know for sure is to follow the suggestion to clear the entire queue before upgrading, which means that this is not a backwards compatible release. A major version increment is justified according to [Semantic Versioning](http://semver.org/).

**Comment by behrad** [comment]
I first considered this releasing 0.10.0 without merging FIFO ordering job id mapping PR, however I was planned kue 1.0 a complete re-write of kue (and didn't like 2.0 naming for that), however I decided to merge that in earlier without dumping major to 1.0

I believe many npm modules are more increasing minors even for large changes instead of majors, so this has became a habit not to increase minor in production without considerations.

We had done this from 0.7 to 0.8 and before... (no to increase major too high) However we can properly test and build an assessment script to migrate data :) Any PR/script is welcome @jeremiahlee

**Comment by jeremiahlee** [comment]
I was reminded on [Twitter](https://twitter.com/izs/status/667823589261881344) that major version 0 has special handling (^0.9 would not match ^0.10), so this is not an issue. Carry on :)

**Comment by behrad** [comment]
Great info @jeremiahlee Thank you for caring :+1:
