### ISSUE TITLE
Architecture Question: express rest api and kue worker

### ISSUE THREAD

**Issue by fabianfett** [Automattic/kue#849]
Hi,

I do have an express rest api service. There are some rest api endpoints that trigger longer running tasks in kue. So far nothing special. On a multicore computer I use pm2 for process management and clustering. 

Though I am concerned on where to put my kue code. As far as I can see I do have two options (assuming I have a four core machine.):
- Put the kue code in the rest api service process. (That means the node process has both running kue and express. Though as long as everything is non blocking I can't see any problems.) To scale I just cluster the node process. (This would make four node processes in total.)
- Create a second node process that is just processing in kue tasks. (That would mean to have completely separate processes.) I can see pros for that as well. But in the end I would have as many as kue processes as express processes (4 each, 8 in total). Integration Testing (two repositories) would become much harder as well.

So what is the best practice on that?

Thanks so much in advance,
  Fabian

**Comment by behrad** [comment]
It depends on your concerns and needs specially in deployment model of yours. Are your rest api & workers needed to talk to each other? with what rates? Do you need isolated deployments start/stops (e.g. your API service is updated more frequently)? Different scaling needs? more workers nodes than APIs?

I'd say start with both in a single process, with separation in mind, and split when needed. and don't run 8  node.js processes on a 4core machine, since node.js is single core, one process can starve  other's event loop :)
