### ISSUE TITLE
Is there a Kue Web API to pause a job?

### ISSUE THREAD

**Issue by mmumshad** [Automattic/kue#965]
In the kue web UI, is there an API to pause a job? I am using the Kue Web API for job management. What would be a good way to pause/stop a worker from my application if not possible through the Kue Web API?

**Comment by behrad** [comment]
No, I think this is the worker's ability to be able to pause/shutdown. You can create an API on top of that in your app.

**Comment by mmumshad** [comment]
Thanks for the information. I am running the worker as a separate process so that it is decoupled from my web server. And I can start jobs using the kue web API. My web application does not directly interact with the worker. I wonder how I could implement a pause or shutdown feature then. I would like to stop/pause a specific job based on the job id. Appreciate any inputs on how would I go about this?

PS: the reason I decoupled my web server and the worker is the worker to continue to run and log messages to the Kue Web UI, even if my web server restarts or goes down. Is this not a good approach?

**Comment by behrad** [comment]
shutdown/pause ability is worker's responsibility. you should send a message to your worker process therefore so that it can call `.pause/.shutdown` in its job context.
You can use any messaging pattern IPC, sockets, websockets, message queues so that your web app process talks to workers.

You may want to use redis pub/sub between them to talk to eachother,
You may want to use an external module for this, like dnode, or websockets modules, ...
